name: Setup TCP BBR v3
description: configure TCP BBR v3
inputs:
  kernel_version:
    description: 'Kernel version (e.g., 6.6)'
    required: true
  android_version:
    description: 'Android version (e.g., 12)'
    required: true

runs:
  using: composite
  steps:
    - name: Extract BBG Version
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/aosp
      run: |
        BBR_ANDROID_VERSION="${{ inputs.android_version }}"
        BBR_KERNEL_VERSION="${{ inputs.kernel_version }}"

        # Android 16 on 6.1 kernels reuses the Android 14 BBR patch set.
        if [[ "$BBR_ANDROID_VERSION" == "android16" && "$BBR_KERNEL_VERSION" == "6.1" ]]; then
          BBR_ANDROID_VERSION="android14"
        fi

        BBR_PATCH="bbrv3-${BBR_ANDROID_VERSION}-${BBR_KERNEL_VERSION}.patch"

        cp "$GITHUB_WORKSPACE/kernel_patches/$BBR_PATCH" $GITHUB_WORKSPACE/kernel/aosp
        patch -p1 < "$BBR_PATCH"

    - name: Fix modules.bzl
      shell: bash
      if: false
      working-directory: ${{ github.workspace }}/kernel/aosp
      run: |
        if [ "$inputs.kernel_version" == "6.1" ]; then
          mods_file=modules.bzl
          for m in "net/ipv4/tcp_bic.ko" "net/ipv4/tcp_htcp.ko" "net/ipv4/tcp_westwood.ko"; do
            grep -q "'$m'" "$mods_file" && continue
            sed -i "/_ARM64_GKI_MODULES_LIST = \[/,/^]/ s/^]/    \"$m\",\n]/" "$mods_file"
          done
        fi

    - name: Add BBRv3 Config
      shell: bash
      working-directory: ${{ github.workspace }}/kernel
      run: |
        cat >> "${{ github.workspace }}/wild_gki.fragment" << 'EOF'
        CONFIG_TCP_CONG_ADVANCED=y
        CONFIG_TCP_CONG_BBR=y
        CONFIG_DEFAULT_BBR=y
        CONFIG_DEFAULT_TCP_CONG="bbr"
        CONFIG_NET_SCH_FQ=y
        # CONFIG_TCP_CONG_BIC is not set
        # CONFIG_TCP_CONG_WESTWOOD is not set
        # CONFIG_TCP_CONG_HTCP is not set
        EOF
        

    
